### PR TITLE
Fix relocating certificate paths to /etc/rhsm-host

### LINKED ISSUE #9: If rhsm.conf is missing but /etc/rhsm-host directory exists, repo_ca_cert gets set to a bogus value: /etc/rhsm-host-host/ca/redhat-uep.pem
If running inside a container and `/etc/rhsm-host/rhsm.conf` does not exist (as on RHCOS where `/etc/rhsm` does not contain the usual config files, only the `ca` directory) then:

1. `rhsm_context_new ` is called, it checks for `/etc/rhsm-host`
2. `/etc/rhsm-host` exists so `in_container` is true
3. `conf_dir ` is set to `/etc/rhsm-host`.
4. `g_key_file_load_from_file ` tries to read `/etc/rhsm-host/rhsm.conf` which does not exist, so it returns null.
  It would be helpful if a warning could be emittedin this case.
5. `rhsm_context_new` calls `g_object_new` specifying `conf-file` as `/etc/rhsm-host/rhsm.conf` and the other five properties (which would have been read from the config file if it existed), including `repo-ca-cert` as null.
6. GObject calls `rhsm_context_constructed`
7. `rhsm_context_constructed` checks each of the properties and upon seeing they are null, provides default values.
8. `repo_ca_cert` gets defaulted to g_build_filename(g_build_filename(dirname("/etc/rhsm-host/rhsm.conf"), "ca"), "redhat-uep.pem") i.e., `/etc/rhsm-host/ca/redhat-uep.pem`
9. Before `rhsm_context_constructed` returns, [it checks](https://github.com/rpm-software-management/librhsm/blob/5e0674cf389f14174208641ec411ba7be448d5e3/rhsm/rhsm-context.c#L541) if `ctx->conf_file` starts with `CONFIG_DIR_HOST`, i.e., `/etc/rhsm-host`; it does.
10. `rhsm_utils_str_replace ` is called to modify the value of `ctx->repo_ca_cert`. It replaces any instances of `/etc/rhsm` with `/ec/rhsm-host`. Before this happens, the value of `repo_ca_cert` was `/etc/rhsm-host/ca/redhat-uep.pem`. Therefore the value of `repo_ca_cert` is changed to `/etc/rhsm-host-host/ca/redhat-uep.pem`.

As a result, if you try to use `microdnf` inside a container running on RHCOS, you get:

```
STEP 7/9: RUN microdnf -y install ipa-client
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
error: cannot update repo 'rhel-8-for-x86_64-baseos-rpms': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [error setting certificate verify locations:
  CAfile: /etc/rhsm-host-host/ca/redhat-uep.pem
  CApath: none]; Last error: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [error setting certificate verify locations:
  CAfile: /etc/rhsm-host-host/ca/redhat-uep.pem
  CApath: none]
error: build error: error building at STEP "RUN microdnf -y install ipa-client": error while running runtime: exit status 1
```

### PR DESCRIPTION
**Pull request by ppisar**
If /etc/rhsm-host directory exists, librhsm corrects CA certificate location (rhsm_context_get_ca_cert_dir()) and YUM repository CA certificate location (rhsm_context_get_repo_ca_cert()) from /etc/rhsm to /etc/rhsm-host prefix.

However, there was a bug in the path relocation and, as a result, the locations were mangled to a wrong /etc/rhsm-host-host prefix.

This patch fixes the relocation algorithm to consider boundaries between the path components.

Note that the relocation was and still is applied not only to default values, but also to values loaded from a configuration file. That's probably on purpose to ease sharing the configuration among a host and the containers.

https://github.com/rpm-software-management/librhsm/issues/9

### CODE REVIEW

**Comment by ppisar** [comment]
This PR replaces #11.

**Comment by HuijingHei** [comment]
Thanks @ppisar , this looks more reasonable.

One minor suggestion is about the `conf_file`, if detect `/etc/rhsm-host`, `conf_file` will be considered as `/etc/rhsm-host/rhsm.conf`, but it does not exist on RHCOS. Do you mind adding the check like https://github.com/rpm-software-management/librhsm/pull/10 ?

```
  /* Check rhsm.conf exists */
  if (!g_file_test (conf_file, G_FILE_TEST_EXISTS))
    g_debug ("Not found config file %s", conf_file);
```

**Comment by ppisar** [comment]
> One minor suggestion is about the `conf_file`, if detect `/etc/rhsm-host`, `conf_file` will be considered as `/etc/rhsm-host/rhsm.conf`, but it does not exist on RHCOS. Do you mind adding the check like #10 ?
> 
> ```
>   /* Check rhsm.conf exists */
>   if (!g_file_test (conf_file, G_FILE_TEST_EXISTS))
>     g_debug ("Not found config file %s", conf_file);
> ```
I opened a separate pull request #13 which adds the debugging message.

**Review by HuijingHei — APPROVED** [review]
LGTM

**Comment by HuijingHei** [comment]
Could someone else help to review and merge? cc @j-mracek

**Comment by j-mracek** [comment]
LGTM

**Comment by j-mracek** [comment]
Thank you @ppisar for the proper patch.

**Pull request merged**
