### PR TITLE
Fix a memory leak

### PR DESCRIPTION
**Pull request by m-blaha**
https://bugzilla.redhat.com/show_bug.cgi?id=1938785

### CODE REVIEW

**Comment by kontura** [comment]
Is it possible this is actually a false positive?

Since [`g_base64_decode_inplace`](https://developer.gnome.org/glib/stable/glib-Base64-Encoding.html#g-base64-decode-inplace) returns: `The binary data that text responds. This pointer is the same as the input text.` so `zdata` is the same as `ent` and then [`g_memory_input_stream_new_from_data`](https://developer.gnome.org/gio/stable/GMemoryInputStream.html#g-memory-input-stream-new-from-data) takes `zdata` and has `g_free` which according to docs is used to free `zdata/ent`?

**Comment by m-blaha** [comment]
Oh, right. I missed the `g_free` in `g_memory_input_stream_new_from_data`. Thanks for spotting this.

**Comment by m-blaha** [comment]
@kontura But still - we should get rid of the covscan warning. I can see two possible solutions right now:

1. add annotation for coverity to suppress the false positive - I do not like it because it's basically noise in the source code. And on top of that on quite unrelated line (`return NULL`)
2. refactor the source code (e.g. remove g_free from g_memory_input_stream_new_from_data). I do not like it either, because original code is currently correct and readable. Refactoring adds nothing except for silencing the false positive alert.

Do we have any other option?

**Comment by kontura** [comment]
Unfortunately I can't think of any other option (we also can't just delete the code it seems used).

Of the two I would prefer the refactor.
I tried the approach you suggested: removing the `g_free` and adding the `g_autofree` like in this PR and it works: https://cov01.lab.eng.brq.redhat.com/covscanhub/task/222952/

**Comment by m-blaha** [comment]
OK, it looks like I cannot re-open changed PR so the new version is here: https://github.com/rpm-software-management/librhsm/pull/8

**Pull request closed without merging**
